Repository AXECAC/Template-Back-End-C-Sharp, pull requests merged in 2025-03, with the labels that each got.

#54 Aragami3070/remake base repository
  Context/Classes/BaseRepository.cs
  Context/Classes/UserRepository.cs
  Context/Interfaces/IBaseRepository.cs
  Context/Interfaces/IUserRepository.cs
Labels: enhancement, database, dotnet

#59 Add: main README
  LICENSE
  README.md
Labels: documentation, enhancement

#61 Aragami3070/fix save endpoint
  Controllers/Controllers/AuthController.cs
  Controllers/Controllers/UserController.cs
  Services/Extentions/UserExtentions.cs
Labels: dotnet, Fix

#73 Aragami3070/updates
  .editorconfig
  Context/Classes/BaseRepository.cs
  Context/Classes/UserRepository.cs
  Controllers/Controllers/UserController.cs
  Controllers/Program.cs
  DataBase/Response/BaseResponse.cs
  DataBase/Response/IBaseResponse.cs
  Fixes.md
  Services/Implementations/AuthServices.cs
  Services/Implementations/TokenServices.cs
  Services/Implementations/UserServices.cs
Labels: enhancement, dotnet, Fix

#79 Aragami3070/BaseRepository FirstOrDefaultAsync add
  Context/Classes/BaseRepository.cs
  Context/Classes/UserRepository.cs
  Context/Interfaces/IBaseRepository.cs
  Context/Interfaces/IUserRepository.cs
  Services/Implementations/UserServices.cs
Labels: enhancement, dotnet

#85 Fix: build error
  Services/Implementations/AuthServices.cs
  Services/Implementations/UserServices.cs
Labels: bug, dotnet, Fix

#88 Aragami3070/add i quariable methods
  Context/Classes/BaseRepository.cs
  Context/Classes/UserRepository.cs
  Context/Interfaces/IBaseRepository.cs
Labels: enhancement, dotnet

#89 Aragami3070/custom middleware
  Controllers/Controllers/UserController.cs
  Controllers/Middlewares/ExceptionHandlerMiddleware.cs
  Controllers/Program.cs
  Services/Implementations/UserServices.cs
Labels: enhancement, dotnet

#81 Anarchy73/RedisAdd
  Context/Classes/BaseRepository.cs
  Context/Classes/UserRepository.cs
  Controllers/Controllers.csproj
  Controllers/Program.cs
  Controllers/appsettings.json
  DataBase/Docker/docker-compose.yml
  Services/Implementations/CachingServices.cs
  Services/Implementations/UserServices.cs
  Services/Interfaces/ICachingServices.cs
  Services/Interfaces/IUserServices.cs
Labels: enhancement, database, dotnet

#94 Anarchy73/russian comments
  .editorconfig
  Context/Classes/BaseRepository.cs
  Context/Classes/UserRepository.cs
  Context/Context.cs
  Context/Interfaces/IBaseRepository.cs
  Context/Interfaces/IUserRepository.cs
  Controllers/Controllers/AuthController.cs
  Controllers/Controllers/UserController.cs
  Controllers/Program.cs
  Controllers/appsettings.json
  DataBase/Entities/LoginUser.cs
  DataBase/Entities/User.cs
  DataBase/Enums/StatusCode.cs
  DataBase/Response/BaseResponse.cs
  DataBase/Response/IBaseResponse.cs
  Services/Extentions/UserExtentions.cs
  Services/Implementations/AuthServices.cs
  Services/Implementations/CachingServices.cs
  Services/Implementations/HashingServices.cs
  Services/Implementations/TokenServices.cs
  Services/Implementations/UserServices.cs
  Services/Interfaces/IAuthServices.cs
  Services/Interfaces/ICachingServices.cs
  Services/Interfaces/IHashingServices.cs
  Services/Interfaces/ITokenServices.cs
  Services/Interfaces/IUserServices.cs
Labels: Fix

#98 Delete: Fixes.md
  Fixes.md
Labels: Fix
