Repository AXECAC/Template-Back-End-C-Sharp, pull requests merged in 2025-02, with the labels that each got.

#23 Aragami3070/user db methods
  Context/Context.cs
  Controllers/Program.cs
  Services/Classes/TestClass.cs
  Services/Classes/UserRepository.cs
  Services/Interfaces/IBaseRepository.cs
  Services/Interfaces/IUserRepository.cs
Labels: enhancement

#24 Sql create table script
  DataBase/Scripts/UserTable.sql
Labels: enhancement

#27 Add: Sql scripts readme
  DataBase/Scripts/Readme.md
Labels: documentation

#30 Aragami3070/user controller etc
  Context/Classes/UserRepository.cs
  Context/Context.csproj
  Context/Interfaces/IBaseRepository.cs
  Context/Interfaces/IUserRepository.cs
  Controllers/Controllers.csproj
  Controllers/Controllers/UserController.cs
  Controllers/Program.cs
  DataBase/Docker/backup.sql
  DataBase/Models/User.cs
  DataBase/Response/BaseResponse.cs
  DataBase/Response/IBaseResponse.cs
  DataBase/Scripts/UserTable.sql
  Fixes.md
  Services/Extentions/UserExtentions.cs
  Services/Implementations/UserServices.cs
  Services/Interfaces/IUserServices.cs
Labels: enhancement, dotnet, Fix

#40 Aragami3070/Remake IResult to IActionResult
  Controllers/Controllers/UserController.cs
Labels: dotnet, Fix

#41 Aragami3070/hashing password
  Controllers/Program.cs
  Services/Implementations/HashingServices.cs
  Services/Implementations/UserServices.cs
  Services/Interfaces/IHashingServices.cs
Labels: enhancement, database, dotnet

#49 Fix: can use swagger with debug
  Controllers/Program.cs
Labels: dotnet, Fix

#50 Fix: attributes in Controllers
  Controllers/Controllers/AuthController.cs
  Controllers/Controllers/UserController.cs
  Services/Implementations/UserServices.cs
Labels: dotnet, Fix

#51 Change: check save/edit and edit from by id -> by old email
  Controllers/Controllers/AuthController.cs
  Controllers/Controllers/UserController.cs
  Services/Extentions/UserExtentions.cs
  Services/Implementations/UserServices.cs
  Services/Interfaces/IUserServices.cs
Labels: enhancement, dotnet

#57 Fix: do Auth controller more readble
  Controllers/Controllers/AuthController.cs
Labels: Fix
